import { MD3Theme, configureFonts } from 'react-native-paper';

const baseFont = {
  fontFamily: 'System',
  letterSpacing: 0,
  fontWeight: '400' as const,
  fontSize: 16,
  lineHeight: 24,
} as const;

const lightTheme: MD3Theme = {
  version: 3,
  isV3: true,
  dark: false,
  mode: 'adaptive',
  roundness: 4,
  colors: {
    primary: '#6750A4',
    primaryContainer: '#EADDFF',
    secondary: '#625B71',
    secondaryContainer: '#E8DEF8',
    tertiary: '#7D5260',
    tertiaryContainer: '#FFD8E4',
    surface: '#FFFBFE',
    surfaceVariant: '#E7E0EC',
    surfaceDisabled: '#1F1F1F',
    background: '#FFFBFE',
    error: '#B3261E',
    errorContainer: '#F9DEDC',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#21005E',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#1E192B',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#370B1E',
    onSurface: '#1C1B1F',
    onSurfaceVariant: '#49454F',
    onSurfaceDisabled: '#1F1F1F',
    onError: '#FFFFFF',
    onErrorContainer: '#410E0B',
    onBackground: '#1C1B1F',
    outline: '#79747E',
    outlineVariant: '#CAC4D0',
    inverseSurface: '#313033',
    inverseOnSurface: '#F4EFF4',
    inversePrimary: '#D0BCFF',
    shadow: 'rgba(0, 0, 0, 0.3)',
    scrim: 'rgba(0, 0, 0, 0.3)',
    elevation: {
      level0: 'transparent',
      level1: '#F7F2FA',
      level2: '#F3EDF7',
      level3: '#EFE9F4',
      level4: '#EFE9F4',
      level5: '#EDE7F2',
    },
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  fonts: configureFonts({
    config: {
      default: baseFont,
    },
    isV3: true,
  }),
  animation: {
    scale: 1.0,
  },
};

const darkTheme: MD3Theme = {
  ...lightTheme,
  dark: true,
  colors: {
    primary: '#D0BCFF',
    primaryContainer: '#4F378B',
    secondary: '#CCC2DC',
    secondaryContainer: '#4A4458',
    tertiary: '#EFB8C8',
    tertiaryContainer: '#633B48',
    surface: '#1C1B1F',
    surfaceVariant: '#49454F',
    surfaceDisabled: '#1F1F1F',
    background: '#1C1B1F',
    error: '#F2B8B5',
    errorContainer: '#8C1D18',
    onPrimary: '#371E73',
    onPrimaryContainer: '#EADDFF',
    onSecondary: '#332D41',
    onSecondaryContainer: '#E8DEF8',
    onTertiary: '#492532',
    onTertiaryContainer: '#FFD8E4',
    onSurface: '#E6E1E5',
    onSurfaceVariant: '#CAC4D0',
    onSurfaceDisabled: '#1F1F1F',
    onError: '#601410',
    onErrorContainer: '#F9DEDC',
    onBackground: '#E6E1E5',
    outline: '#938F99',
    outlineVariant: '#49454F',
    inverseSurface: '#E6E1E5',
    inverseOnSurface: '#313033',
    inversePrimary: '#6750A4',
    shadow: 'rgba(0, 0, 0, 0.5)',
    scrim: 'rgba(0, 0, 0, 0.5)',
    elevation: {
      level0: 'transparent',
      level1: '#27232F',
      level2: '#2B2930',
      level3: '#2E2C31',
      level4: '#2E2C31',
      level5: '#302D34',
    },
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
};

export { lightTheme, darkTheme };
